version: '3.8'

services:
  sms:
    image: altipeak/sms:latest
    ports:
      - published: 9999
        target: 9999
        protocol: tcp
    environment:
      # Redis      
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=l10hlfop4e4JXk9a
    depends_on:
      - "redis"

  redis:
    image: bitnami/redis:7.0
    environment:
      - REDIS_PASSWORD=l10hlfop4e4JXk9a
    volumes:
      - 'redis-data:/bitnami/redis'

volumes:
  redis-data:
